### ISSUE TITLE
`css` prop does not work when @emotion/react is added as dependency

### ISSUE THREAD

**Issue by filipebarcos** [verygoodsecurity/collect-js-react#58]
## Expected Behavior
`css` property work even when app has `@emotion/react` as dependency

## Current Behavior
Currently, if you have plain app that does not depend on `@emotion/react`, `css` prop from `<VGSCollectForm>` and its fields work like a charm. Although, if your app has `@emotion/react` as dependency the prop gets overloaded.

## Possible Solution
Rename `css` prop to `customStyles` could work.

## Steps to Reproduce (for bugs)

I created this sample app to reproduce it: https://github.com/filipebarcos/my-vgs-app

## Context

We're trying to launch our VGS form with our custom styles and currently, we can't style the form field fonts, for example.

**Comment by flor-master** [comment]
Hi @filipebarcos, could you provide more details about the issue or what you are trying to do? 
I ran your example successfully without any errors. I also tried applying styles from @emotion/react to the Collect iframe wrapper like this, and it also worked on my end.

```JavaScript
import { Global } from '@emotion/react'
 <Global
  styles={{
    '.vgs-collect-iframe-wr': {
      height: '42px',
      width: '320px',
      border: 'solid 1px;'
    },
    '.vgs-collect-iframe-wr iframe': {
      widrth: '100%',
      height: '100%'
    }
  }}
/>
```
Env:
Node: 18.20.3
Vite: 5.4.9

**Comment by flor-master** [comment]
Thanks for the update, now i see the issue, let me take a look

**Comment by flor-master** [comment]
Looks like `@emotion/react` removed `css` property from the component and tried to apply it as the default CSS style. 
We will provide the fix in the next version or share a workaround, soon

**Comment by flor-master** [comment]
Hi! It seems that @emotion/react treats the `css` property as a reserved attribute, and unfortunately, there’s no way to change this. What @emotion/react does isn’t compatible with how the CollectJS SDK operates.

To resolve this issue, we’ve implemented a fallback in version `1.3.1`. To use it, simply replace `css` with `style`.

**Comment by flor-master** [comment]
Example:
```JavaScript
  <VGSCollectForm.TextField
    name="text"
    placeholder="Text"
    style={{color: 'red'}}
  />
```

**Comment by flor-master** [comment]
Hi @filipebarcos I'm back with updates 
I merged an example with font-face here -> https://github.com/verygoodsecurity/collect-js-react/blob/main/example/src/features/CustomPayload.tsx#L26-L37

I download font-face from Google Fonts. Unfortunately, I can't test your example because your CDN restricted my location

**Comment by flor-master** [comment]
> Type '{ fontFamily: string; fontSize: string; }' is not assignable to type 'Record<string, any> & string'
To resolve it - update `collect-js-react` wrapper and rebuild example project
